### ISSUE TITLE
no such file to load -- net/ldap

### ISSUE THREAD

**Issue by skrussell** [xaque208/puppet-ldapquery#10]
Hi,

I've followed your instructions, but for whatever reason, puppet is unable to load your module; it fails with the message:
`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Could not autoload puppet/parser/functions/ldapquery: no such file to load -- net/ldap`

I have installed the puppet gem as required per your instructions:
`# gem list | grep net-ldap
net-ldap (0.16.0)`

However, as I'm using puppetserver, I have also installed it using the local puppetserver gem command (and restarted puppetserver):
`# /opt/puppetlabs/puppet/bin/gem list | grep net-ldap
net-ldap (0.16.0)`
(This is how I have installed all other previous gems that are required for puppet server, including hiera_eyaml, which work fine.

Just to 100% confirm, this gem is installed within the puppet framework:
`# ls -l /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/net-ldap-0.16.0/lib/net/ldap.rb 
-rw-r--r-- 1 root root 55464 Jul 20 14:14 /opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/net-ldap-0.16.0/lib/net/ldap.rb`

Any ideas what is wrong? I highly doubt this is something specific to your module (i.e., I don't think it's a problem with your module), but I've pretty much exhausted all avenues for what to check next.

Thanks in-advance.

**Comment by skrussell** [comment]
Bah, nevermind, I've worked out what I'm doing wrong!

**Comment by xaque208** [comment]
Cool.  Glad you got it going.  I'm happy to help if there are other issues.
